### ISSUE TITLE
Include Python3 Support in pypi package

### ISSUE THREAD

**Issue by ma0c** [chrisballinger/python-localizable#3]
Hello, 

I just try this repo and works just fine, however, the version [inside pypi](https://pypi.org/project/localizable/) doesn't include the latest [merged commit](https://github.com/chrisballinger/python-localizable/commit/15d3bf2466d0de1a826d3f0ff1f365b0c1910f56) including the Python3 compatibility.

Would be great if you upload the latest version into pypi to install the package directly.

Thanks for your time,

Have a great day.

Ma0

**Comment by srkiNZ84** [comment]
I've also hit this issue. Would be nice to have the latest code with Python 3 support in pip if possible.

**Comment by chrisballinger** [comment]
resolved https://pypi.org/project/localizable/0.1.3/
